/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as AppointmentsTableRouteImport } from './routes/appointments/table'
import { Route as TeamMembersIndexRouteImport } from './routes/team/members/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsTableRoute = AppointmentsTableRouteImport.update({
  id: '/appointments/table',
  path: '/appointments/table',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamMembersIndexRoute = TeamMembersIndexRouteImport.update({
  id: '/team/members/',
  path: '/team/members/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments/table': typeof AppointmentsTableRoute
  '/services': typeof ServicesIndexRoute
  '/team/members': typeof TeamMembersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments/table': typeof AppointmentsTableRoute
  '/services': typeof ServicesIndexRoute
  '/team/members': typeof TeamMembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments/table': typeof AppointmentsTableRoute
  '/services/': typeof ServicesIndexRoute
  '/team/members/': typeof TeamMembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/appointments/table' | '/services' | '/team/members'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/appointments/table' | '/services' | '/team/members'
  id: '__root__' | '/' | '/appointments/table' | '/services/' | '/team/members/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsTableRoute: typeof AppointmentsTableRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  TeamMembersIndexRoute: typeof TeamMembersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/table': {
      id: '/appointments/table'
      path: '/appointments/table'
      fullPath: '/appointments/table'
      preLoaderRoute: typeof AppointmentsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/members/': {
      id: '/team/members/'
      path: '/team/members'
      fullPath: '/team/members'
      preLoaderRoute: typeof TeamMembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsTableRoute: AppointmentsTableRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  TeamMembersIndexRoute: TeamMembersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
