/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamIndexRouteImport } from './routes/team/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as AppointmentsIndexRouteImport } from './routes/appointments/index'
import { Route as ServicesTableRouteImport } from './routes/services/table'
import { Route as AppointmentsTableRouteImport } from './routes/appointments/table'
import { Route as TeamSchedulesIndexRouteImport } from './routes/team/schedules/index'
import { Route as TeamMembersIndexRouteImport } from './routes/team/members/index'
import { Route as SettingsPreferencesIndexRouteImport } from './routes/settings/preferences/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsIndexRoute = AppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTableRoute = ServicesTableRouteImport.update({
  id: '/services/table',
  path: '/services/table',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsTableRoute = AppointmentsTableRouteImport.update({
  id: '/appointments/table',
  path: '/appointments/table',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamSchedulesIndexRoute = TeamSchedulesIndexRouteImport.update({
  id: '/team/schedules/',
  path: '/team/schedules/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamMembersIndexRoute = TeamMembersIndexRouteImport.update({
  id: '/team/members/',
  path: '/team/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPreferencesIndexRoute =
  SettingsPreferencesIndexRouteImport.update({
    id: '/settings/preferences/',
    path: '/settings/preferences/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments/table': typeof AppointmentsTableRoute
  '/services/table': typeof ServicesTableRoute
  '/appointments': typeof AppointmentsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/team': typeof TeamIndexRoute
  '/settings/preferences': typeof SettingsPreferencesIndexRoute
  '/team/members': typeof TeamMembersIndexRoute
  '/team/schedules': typeof TeamSchedulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments/table': typeof AppointmentsTableRoute
  '/services/table': typeof ServicesTableRoute
  '/appointments': typeof AppointmentsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/team': typeof TeamIndexRoute
  '/settings/preferences': typeof SettingsPreferencesIndexRoute
  '/team/members': typeof TeamMembersIndexRoute
  '/team/schedules': typeof TeamSchedulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments/table': typeof AppointmentsTableRoute
  '/services/table': typeof ServicesTableRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/team/': typeof TeamIndexRoute
  '/settings/preferences/': typeof SettingsPreferencesIndexRoute
  '/team/members/': typeof TeamMembersIndexRoute
  '/team/schedules/': typeof TeamSchedulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments/table'
    | '/services/table'
    | '/appointments'
    | '/services'
    | '/settings'
    | '/team'
    | '/settings/preferences'
    | '/team/members'
    | '/team/schedules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments/table'
    | '/services/table'
    | '/appointments'
    | '/services'
    | '/settings'
    | '/team'
    | '/settings/preferences'
    | '/team/members'
    | '/team/schedules'
  id:
    | '__root__'
    | '/'
    | '/appointments/table'
    | '/services/table'
    | '/appointments/'
    | '/services/'
    | '/settings/'
    | '/team/'
    | '/settings/preferences/'
    | '/team/members/'
    | '/team/schedules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsTableRoute: typeof AppointmentsTableRoute
  ServicesTableRoute: typeof ServicesTableRoute
  AppointmentsIndexRoute: typeof AppointmentsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TeamIndexRoute: typeof TeamIndexRoute
  SettingsPreferencesIndexRoute: typeof SettingsPreferencesIndexRoute
  TeamMembersIndexRoute: typeof TeamMembersIndexRoute
  TeamSchedulesIndexRoute: typeof TeamSchedulesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/': {
      id: '/appointments/'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/table': {
      id: '/services/table'
      path: '/services/table'
      fullPath: '/services/table'
      preLoaderRoute: typeof ServicesTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/table': {
      id: '/appointments/table'
      path: '/appointments/table'
      fullPath: '/appointments/table'
      preLoaderRoute: typeof AppointmentsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/schedules/': {
      id: '/team/schedules/'
      path: '/team/schedules'
      fullPath: '/team/schedules'
      preLoaderRoute: typeof TeamSchedulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/members/': {
      id: '/team/members/'
      path: '/team/members'
      fullPath: '/team/members'
      preLoaderRoute: typeof TeamMembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/preferences/': {
      id: '/settings/preferences/'
      path: '/settings/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsTableRoute: AppointmentsTableRoute,
  ServicesTableRoute: ServicesTableRoute,
  AppointmentsIndexRoute: AppointmentsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TeamIndexRoute: TeamIndexRoute,
  SettingsPreferencesIndexRoute: SettingsPreferencesIndexRoute,
  TeamMembersIndexRoute: TeamMembersIndexRoute,
  TeamSchedulesIndexRoute: TeamSchedulesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
