/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChooseServiceRouteImport } from './routes/choose-service'
import { Route as ServiceIdRouteImport } from './routes/$serviceId'
import { Route as IndexRouteImport } from './routes/index'

const ChooseServiceRoute = ChooseServiceRouteImport.update({
  id: '/choose-service',
  path: '/choose-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceIdRoute = ServiceIdRouteImport.update({
  id: '/$serviceId',
  path: '/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$serviceId': typeof ServiceIdRoute
  '/choose-service': typeof ChooseServiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$serviceId': typeof ServiceIdRoute
  '/choose-service': typeof ChooseServiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$serviceId': typeof ServiceIdRoute
  '/choose-service': typeof ChooseServiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$serviceId' | '/choose-service'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$serviceId' | '/choose-service'
  id: '__root__' | '/' | '/$serviceId' | '/choose-service'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServiceIdRoute: typeof ServiceIdRoute
  ChooseServiceRoute: typeof ChooseServiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/choose-service': {
      id: '/choose-service'
      path: '/choose-service'
      fullPath: '/choose-service'
      preLoaderRoute: typeof ChooseServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$serviceId': {
      id: '/$serviceId'
      path: '/$serviceId'
      fullPath: '/$serviceId'
      preLoaderRoute: typeof ServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServiceIdRoute: ServiceIdRoute,
  ChooseServiceRoute: ChooseServiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
